#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 22 23:17:06 2022

@author: heisenberg
"""

import numpy as np
import glob
from PIL import Image, ImageDraw, ImageFilter

path_1 = "/home/heisenberg/Study/Database/New_Rsearch/img/dst_imgs/bin_2_result/*.*"
path_2 = "/home/heisenberg/Study/Database/New_Rsearch/img/img_for_add/bin/*.*"
img_number = 1

for file in glob.glob(path_1):
    img_1 = Image.open(file)
    for file in glob.glob(path_2):
        img_2 = Image.open(file)
        back_im = img_1.copy()
        back_im.paste(img_2, (700,300))
        back_im.save('/home/heisenberg/Study/Database/New_Rsearch/img/abc/bin_1/G1_img_'+str(img_number)+'.jpg')
        img_number +=1