#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 14 22:25:22 2022

@author: heisenberg
"""

import cv2
import numpy as np

img = cv2.imread('/home/heisenberg/Study/Database/Gupi Gyne Bagha Byne/Gupi Gain0032.jpg', cv2.IMREAD_UNCHANGED)

#convert img to grey
img_grey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#set a thresh
thresh = 100
#get threshold image
ret,thresh_img = cv2.threshold(img_grey, thresh, 255, cv2.THRESH_BINARY)
#find contours
"""contours, hierarchy = cv2.findContours(thresh_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

#create an empty image for contours
img_contours = np.zeros(img.shape)
# draw the contours on the empty image
cv2.drawContours(img_contours, contours, -1, (0,255,0), 1)
#save image
cv2.imwrite('/home/heisenberg/Study/Database/GGBB_Output/GGBB32_Contours.jpg',img_contours)
"""

contours, _ = cv2.findContours(thresh_img, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
for c in contours:
    rect = cv2.boundingRect(c)
    if rect[2] < 100 or rect[3] < 100: continue
    area=cv2.contourArea(c)
    print(area)
x,y,w,h = rect
cv2.rectangle(thresh_img,(x,y),(x+w,y+h),(0,255,0),2)
cv2.putText(thresh_img,'Moth Detected',(x+w+10,y+h),0,0.3,(0,255,0))
cv2.imwrite('/home/heisenberg/Study/Database/GGBB_Output/GGBB32_Contours.jpg',thresh_img)
'''cv2.imshow("Show",thresh_img)
cv2.waitKey()  
cv2.destroyAllWindows()'''