#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr  6 19:22:36 2022

@author: heisenberg
"""

import cv2
import glob

path=glob.glob("/home/heisenberg/Study/Database/words/a01/a01-000u/*.png")

for file in path:
    img=cv2.imread(file)
    height=img.shape[0]
    width=img.shape[1]
    cv2.line(img,(0,0),(27,51),(255,0,0),3,lineType=cv2.LINE_8,shift=None)
    cv2.imwrite("/home/heisenberg/Study/Database/striked words/",img)
    
